/**
 * GOLDEN FIXTURE — a hand-computed over that exercises every awkward rule at once.
 *
 * This is a synthetic innings whose expected figures were worked out by hand,
 * NOT generated by running the engine. That is the point: if the engine is
 * wrong, this test fails.
 *
 * Before the hackathon demo you should ALSO replay one real innings from a
 * published scorecard (see replayRealInnings.md) — a synthetic fixture proves
 * internal consistency, a real one proves you agree with the rest of the world.
 *
 * Hand-worked ball by ball:
 *
 *  #  delivery                    total  legal  striker after
 *  1  A hits 1                     1/0     1    B   (odd run -> swap)
 *  2  wide                         2/0     1    B   (not legal, batter faces nothing)
 *  3  B hits 4                     6/0     2    B
 *  4  no-ball, 1 off bat           8/0     2    A   (1 nb + 1 bat; odd -> swap; FREE HIT)
 *  5  wide (free hit persists)     9/0     2    A
 *  6  free hit, "bowled"           9/0     3    A   (not out; A faces it)
 *  7  leg bye 1                   10/0     4    B   (odd -> swap; A faced it)
 *  8  dot                         10/0     5    B
 *  9  B caught, not crossed       10/1     6    A   (C in at striker end,
 *                                                    then over ends -> ends swap)
 *
 *  Final: 10/1 in 1.0 over
 *    A  1 run  off 3 balls   (deliveries 1, 6, 7)
 *    B  5 runs off 4 balls   (deliveries 3, 4, 8, 9) — out caught
 *    C  0 runs off 0 balls
 *    Extras 4 = w2 + nb1 + lb1
 *    Check: 1 + 5 + 4 = 10 ✓
 *    Bowler X: 6 legal balls, conceded 1+4+1 (bat) + 2 (wides) + 1 (nb) = 9, 1 wicket
 *    Check: 9 + 1 leg bye = 10 ✓
 */
import { describe, it, expect } from 'vitest';
import { derive, formatOvers, totalExtras, battingCard } from '../derive';
import { ball, RULES, OPENING } from './helpers';
import type { BallEvent } from '../types';

const INNINGS: BallEvent[] = [
  ball({ strikerId: 'A', nonStrikerId: 'B', runsOffBat: 1 }),
  ball({ strikerId: 'B', nonStrikerId: 'A', extraType: 'WIDE' }),
  ball({ strikerId: 'B', nonStrikerId: 'A', runsOffBat: 4 }),
  ball({ strikerId: 'B', nonStrikerId: 'A', extraType: 'NO_BALL', runsOffBat: 1 }),
  ball({ strikerId: 'A', nonStrikerId: 'B', extraType: 'WIDE' }),
  ball({
    strikerId: 'A',
    nonStrikerId: 'B',
    wicket: { kind: 'BOWLED', outPlayerId: 'A' }, // free hit -> not out
  }),
  ball({ strikerId: 'A', nonStrikerId: 'B', extraType: 'LEG_BYE', extraRuns: 1 }),
  ball({ strikerId: 'B', nonStrikerId: 'A' }),
  ball({
    strikerId: 'B',
    nonStrikerId: 'A',
    wicket: { kind: 'CAUGHT', outPlayerId: 'B', fielderId: 'F', crossed: false },
    newBatterId: 'C',
  }),
];

describe('golden fixture: one hand-computed over', () => {
  const s = derive(INNINGS, RULES, OPENING);

  it('scoreline is 10/1 in exactly 1.0 over', () => {
    expect(s.runs).toBe(10);
    expect(s.wickets).toBe(1);
    expect(s.legalBalls).toBe(6);
    expect(formatOvers(s.legalBalls)).toBe('1.0');
  });

  it('extras break down as w2 nb1 lb1 b0', () => {
    expect(s.extras).toEqual({ wides: 2, noBalls: 1, byes: 0, legByes: 1 });
    expect(totalExtras(s)).toBe(4);
  });

  it('batting card matches', () => {
    expect(s.batters['A']).toMatchObject({ runs: 1, balls: 3, fours: 0, sixes: 0, out: null });
    expect(s.batters['B']).toMatchObject({ runs: 5, balls: 4, fours: 1, sixes: 0 });
    expect(s.batters['B']!.out?.kind).toBe('CAUGHT');
    expect(s.batters['C']).toMatchObject({ runs: 0, balls: 0, out: null });
  });

  it('bowling figures match', () => {
    expect(s.bowlers['X']).toMatchObject({ balls: 6, runs: 9, wickets: 1, maidens: 0 });
    expect(formatOvers(s.bowlers['X']!.balls)).toBe('1.0');
  });

  it('the accounting closes both ways', () => {
    const batRuns = Object.values(s.batters).reduce((a, b) => a + b.runs, 0);
    expect(batRuns + totalExtras(s)).toBe(s.runs);
    // bowler's runs + runs not charged to him (byes + leg byes) = team total
    expect(s.bowlers['X']!.runs + s.extras.byes + s.extras.legByes).toBe(s.runs);
  });

  it('ends are correct after the over: A on strike, C at the other end', () => {
    expect(s.strikerId).toBe('A');
    expect(s.nonStrikerId).toBe('C');
  });

  it('the free hit was consumed and the bowler is locked out of the next over', () => {
    expect(s.freeHitNext).toBe(false);
    expect(s.previousBowlerId).toBe('X');
  });

  it('batting order is arrival order', () => {
    expect(battingCard(s).map((b) => b.playerId)).toEqual(['A', 'B', 'C']);
  });
});
